# Ingress patch to use NodePort/HostPort instead of LoadBalancer
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: placeholder
  annotations:
    # Remove AWS ALB annotations
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "self-signed"
spec:
  ingressClassName: traefik
