apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aethercore

resources:
  - namespace.yaml

commonLabels:
  project: AetherCore
  managed-by: kustomize

commonAnnotations:
  description: "AetherCore base Kubernetes resources"
